/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DotwellKnownHostMetaRouteImport } from './routes/[.]well-known/host-meta'
import { Route as DotwellKnownWebfingerRouteImport } from './routes/[.]well-known/webfinger'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ResourceSplatRouteImport } from './routes/resource.$'
import { Route as UsernameSearchQueryRouteImport } from './routes/$username.search.$query'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownHostMetaRoute = DotwellKnownHostMetaRouteImport.update({
  id: '/.well-known/host-meta',
  path: '/.well-known/host-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownWebfingerRoute = DotwellKnownWebfingerRouteImport.update({
  id: '/.well-known/webfinger',
  path: '/.well-known/webfinger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceSplatRoute = ResourceSplatRouteImport.update({
  id: '/resource/$',
  path: '/resource/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameSearchQueryRoute = UsernameSearchQueryRouteImport.update({
  id: '/$username/search/$query',
  path: '/$username/search/$query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/.well-known/host-meta': typeof DotwellKnownHostMetaRoute
  '/.well-known/webfinger': typeof DotwellKnownWebfingerRoute
  '/api/$': typeof ApiSplatRoute
  '/resource/$': typeof ResourceSplatRoute
  '/$username/search/$query': typeof UsernameSearchQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/.well-known/host-meta': typeof DotwellKnownHostMetaRoute
  '/.well-known/webfinger': typeof DotwellKnownWebfingerRoute
  '/api/$': typeof ApiSplatRoute
  '/resource/$': typeof ResourceSplatRoute
  '/$username/search/$query': typeof UsernameSearchQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/.well-known/host-meta': typeof DotwellKnownHostMetaRoute
  '/.well-known/webfinger': typeof DotwellKnownWebfingerRoute
  '/api/$': typeof ApiSplatRoute
  '/resource/$': typeof ResourceSplatRoute
  '/$username/search/$query': typeof UsernameSearchQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/.well-known/host-meta'
    | '/.well-known/webfinger'
    | '/api/$'
    | '/resource/$'
    | '/$username/search/$query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/.well-known/host-meta'
    | '/.well-known/webfinger'
    | '/api/$'
    | '/resource/$'
    | '/$username/search/$query'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/.well-known/host-meta'
    | '/.well-known/webfinger'
    | '/api/$'
    | '/resource/$'
    | '/$username/search/$query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRoute
  DotwellKnownHostMetaRoute: typeof DotwellKnownHostMetaRoute
  DotwellKnownWebfingerRoute: typeof DotwellKnownWebfingerRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ResourceSplatRoute: typeof ResourceSplatRoute
  UsernameSearchQueryRoute: typeof UsernameSearchQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/host-meta': {
      id: '/.well-known/host-meta'
      path: '/.well-known/host-meta'
      fullPath: '/.well-known/host-meta'
      preLoaderRoute: typeof DotwellKnownHostMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/webfinger': {
      id: '/.well-known/webfinger'
      path: '/.well-known/webfinger'
      fullPath: '/.well-known/webfinger'
      preLoaderRoute: typeof DotwellKnownWebfingerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/$': {
      id: '/resource/$'
      path: '/resource/$'
      fullPath: '/resource/$'
      preLoaderRoute: typeof ResourceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/search/$query': {
      id: '/$username/search/$query'
      path: '/$username/search/$query'
      fullPath: '/$username/search/$query'
      preLoaderRoute: typeof UsernameSearchQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRoute,
  DotwellKnownHostMetaRoute: DotwellKnownHostMetaRoute,
  DotwellKnownWebfingerRoute: DotwellKnownWebfingerRoute,
  ApiSplatRoute: ApiSplatRoute,
  ResourceSplatRoute: ResourceSplatRoute,
  UsernameSearchQueryRoute: UsernameSearchQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
