name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-NODE-18-${{ hashFiles('**/yarn.lock', '**/schema.prisma') }}
      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Alex
        run: yarn alex
      - name: Run ESLint
        run: yarn lint
      - name: Run tests
        run: yarn test:ci
      - name: Run type-check
        run: yarn type-check
